services:
  hybrid-node:
    image: buildonhybrid/hybrid-node:latest
    container_name: hybrid-node
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - &autoupdate com.centurylinklabs.watchtower.scope=hybrid-node

  autoupdate:
    image: containrrr/watchtower:1.7.1
    container_name: hybrid-node-autoupdate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 10800
      WATCHTOWER_LABEL_ENABLE: true
    labels:
      - *autoupdate
